name: A home for dogs, cats and snakes
url: https://qinghe.github.io/

exclude: [bibble, README.md, Makefile, screenshot.png]

# colorize code snippets with the pygments module
highlighter: pygments

# The path structure for blog posts.
permalink: /blog/:year/:month/:day/:title.html
encoding: utf-8
# Sections on the "animals" page.
roles:
  - key: Dogs
    name: dog food and supplies
  - key: Cats
    name: cat food and supplies
  - key: Reptiles
    name: reptile food and supplies
  - key: Others
    name: derivative products

# Number of news stories on the front page.
front_page_news: 8

# Base pathname for links.
base: ''

# make pages for the _projects folder
collections:
  projects:
    output: true

# Navigation bar links.
navigation:
  - title: 主页 Home
    link: /
  - title: 科研项目 Research
    link: /research.html
  - title: 论文 Publications
    link: /publications.html
